# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58f0445bd93db4aabda62785cc83dd5fd01a945bccb0c3e00dfac24656ed65ab8d3f2234acfc33ca45371d1d77c6cadfb6440a29a0a97f1d7bcd7e0e4d858237

test:
  secret_key_base: 2d4f7025c25eee447ca835c0fd1fdf8be73027081409f8bd119ce15099ba928af244f638c5a5716e5a52eb66c7c04d5babdde3f2d2b914ac3af02e25d975fadf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
